apiVersion: apps/v1
kind: Deployment
metadata:
  name: delichat-app
  namespace: delichat
spec:
  template:
    spec:
      containers:
        - name: delichat-app
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
