apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: delichat
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
