apiVersion: v1
kind: Service
metadata:
  name: delichat-app
  namespace: delichat
  labels:
    app: delichat-app
spec:
  selector:
    app: delichat-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
